ConsomiTounsi.web/Controllers/BackController.cs
using ConsomiTounsi.domain.Entities;
using ConsomiTounsi.service;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ConsomiTounsi.web.Controllers
{
    public class BackController : Controller
    {
        IUserService US;
        IContactService ContServ;
        public BackController()
        {
            US = new UserService();
            ContServ = new ContactService();
        }
        // GET: Back
        public ActionResult Index()
        {
            bool val1 = (System.Web.HttpContext.Current.User != null) && System.Web.HttpContext.Current.User.Identity.IsAuthenticated;

            if (!val1)
                return View();
            var userId = User.Identity.GetUserId();
            string UserName = US.GetById(userId).UserName;
            string Phone = US.GetById(userId).Phone;
            string mail = US.GetById(userId).Email;
            ViewBag.Email = mail;
            ViewBag.phone = Phone;
            ViewBag.UserName = UserName;
            ViewBag.authenticated = val1;
            return View(US.GetMany());
        }
        // GET: Back
        public ActionResult IndexContact()
        {
            bool val1 = (System.Web.HttpContext.Current.User != null) && System.Web.HttpContext.Current.User.Identity.IsAuthenticated;

            if (!val1)
                return View();
            var userId = User.Identity.GetUserId();
            string UserName = US.GetById(userId).UserName;
            string Phone = US.GetById(userId).Phone;
            string mail = US.GetById(userId).Email;
            ViewBag.Email = mail;
            ViewBag.phone = Phone;
            ViewBag.UserName = UserName;
            ViewBag.authenticated = val1;
            return View(ContServ.GetMany());
        }
        // GET: Back/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Back/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Back/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Back/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Back/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Back/Delete/5
        public ActionResult Delete(int id)
        {
            var userId = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

             //User.Identity.GetUserId<string>();
            User u = US.GetById(userId);

            if (userId == null)
            {
                return HttpNotFound();
            }

            US.Delete(u);
            US.Commit();
            return RedirectToAction("Index");
        }
    }
}

ConsomiTounsi.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/CSS/bootstrap.min.css")
    @Styles.Render("~/CSS/style.css")
    @Styles.Render("~/CSS/ionicons.min.css")
    @Styles.Render("~/CSS/font-awesome.min.css")
    @Styles.Render("~/CSS/wish/card.css")
    @Styles.Render("~/CSS/wish/Style-NotFound.css")


    <link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:700,900" rel="stylesheet">

</head>
<body>
    <!-- Header
        ================================================= -->
    <header id="header">
        <nav class="navbar navbar-default navbar-fixed-top menu">
            <div class="container">

                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- <a class="navbar-brand" href="index.html"><img src="images/logo.ico" alt="logo" /></a> -->
                    <b><a class="navbar-brand" href="index.html"><p style="color:white">619|Consomi Tounsi</p></a></b>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right main-menu">
                        <li class="dropdown">
                            @Html.ActionLink("Products", "Index", "Productt")
                        </li>
                        <li class="dropdown">
                            @Html.ActionLink("Rayon", "IndexClient", "Rayon")
                        </li>

                        @*@Html.ActionLink(".", "Index", "LigneCommand")*@
                        <li>
                            <button type="button" onclick="location.href='@Url.Action("Index", "LigneCommand")'" style="background-color:black;margin-top:8px;color:white" class="btn btn-dark" value="Bag" id="card">Bag</button>
                        </li>
                        <li>
                            <button type="button" style="background-color:black;margin-top:8px;color:white" class="btn btn-dark" value="clear" id="clear">clear</button>
                        </li>
                        <li class="dropdown">
                            @Html.ActionLink("Posts", "Create", "Post")
                        </li>

                        <li class="dropdown open">
                            <a href="#" class="dropdown-toggle pages" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Transform lives <span><img src="~/images/down-arrow.png" alt=""></span></a>
                            <ul class="dropdown-menu page-list">
                                <li style="color:burlywood">
                                    @Html.ActionLink("Wish Stories", "Index", "Wishes")
                                </li>
                                <li style="color:burlywood">
                                    @Html.ActionLink("Wishes you fundraised", "WishesFundRaisedByAFundRaiser", "Wishes")
                                </li>
                                <li>
                                    @Html.ActionLink("Make a Wish Come True", "Create", "FundRaisers")
                                </li>
                                <li>
                                    @Html.ActionLink("About", "About", "Wishes")
                                </li>
                            </ul>
                        </li>
                        @*<li class="dropdown"><a href="index.html">Log Out</a></li>*@
                        <li class="dropdown open">
                            <a href="#" class="dropdown-toggle pages" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Hello, @ViewBag.Username <span><img src="~/images/down-arrow.png" alt=""></span></a>
                            <ul class="dropdown-menu page-list">
                                <li style="color:burlywood"><i class="material-icons add_ic_call">&#xe97c;</i>@ViewBag.phone</li>
                                <li style="color:burlywood"><i class="material-icons email">&#xe0be;</i>@ViewBag.Email</li>
                                <li>
                                    @if (@ViewBag.authenticated == null)
                                    {
                                        @Html.ActionLink("Login", "Login", "Account")
                                    }
                                    else
                                    {
                                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                        {
                                            @Html.AntiForgeryToken()
                                            <a href="javascript:document.getElementById('logoutForm').submit()" style="text-align:center"><i class="material-icons supervisor_account">&#xe8d3;</i>Log off</a>
                                        }
                                    }
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-right hidden-sm">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search products">
                            <button type="submit" class="btn btn-sm">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
    </header>
    <!--Header End-->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <!-- Footer
        ================================================= -->
        <footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-wrapper">
                        <div class="col-md-3 col-sm-3">
                            <a href=""><h3>619|Consomi Tounsi</h3></a>
                            <ul class="list-inline social-icons">
                                <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-sm-2">
                            <h6>For individuals</h6>
                            <ul class="footer-links">
                                <li>@Html.ActionLink("Sign Up", "Register", "Account")</li>
                                <li>@Html.ActionLink("Login", "Login", "Account")</li>
                                <li><a href="">Explore</a></li>
                                <li><a href="">Features</a></li>
                                <li><a href="">Language settings</a></li>
                            </ul>
                        </div>

                        <div class="col-md-2 col-sm-2">
                            <h6>@Html.ActionLink("About", "About", "Home")</h6>
                            <ul class="footer-links">
                                <li><a href="">@Html.ActionLink("About us", "About", "Home")</a></li>
                                <li><a href="">@Html.ActionLink("Contact Us", "CreateContact", "Home")</a></li>
                                <li><a href="">Privacy Policy</a></li>
                                <li><a href="">Terms</a></li>
                                <li><a href="">Help</a></li>
                            </ul>
                        </div>
                        <div class="col-md-3 col-sm-3">
                            <h6>@Html.ActionLink("Contact Us", "CreateContact", "Home")</h6>
                            <ul class="contact">
                                <li><i class="fa fa-phone"></i> +216 969 25801</li>
                                <li><i class="fa fa-mail-forward"></i> ConsomiTounsi@gmail.com</li>
                                <li><i class="fa fa-location-arrow"></i> Pôle Technologique El Ghazela</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <p>Copyright Consomi Tounis 2020. All rights reserved</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- Scripts
    ================================================= -->
    @Scripts.Render("~/Scripts/JS/jquery-3.1.1.min.js")
    @Scripts.Render("~/Scripts/JS/bootstrap.min.js")
    @Scripts.Render("~/Scripts/JS/jquery.appear.min.js")
    @Scripts.Render("~/Scripts/JS/script.js")
    @Scripts.Render("~/Scripts/JS/list.min.js")

</body>
</html>

ConsomiTounsi.web/Views/Shared/_LayoutBack.cshtml
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Consomi Tounsi Admin - Dashboard</title>

    <!-- Custom fonts for this template-->
    @Styles.Render("~/ContentAdmin/vendor/fontawesome-free/css/all.min.css")

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    @Styles.Render("~/ContentAdmin/css/sb-admin-2.min.css")

    @*@Styles.Render("~/CSS/bootstrap.min.css")*@
    @Styles.Render("~/CSS/style.css")
    @Styles.Render("~/CSS/ionicons.min.css")
    @Styles.Render("~/CSS/font-awesome.min.css")

</head>
<html>
<body id="page-top">
    <!-- Header
           ================================================= -->
    <header id="header">
        <nav class="navbar navbar-default navbar-fixed-top menu" style="background-color:#D9DEE4; width:1465px; margin-left:223px">
            <div class="container">
                    <!-- <a class="navbar-brand" href="index.html"><img src="images/logo.ico" alt="logo" /></a> -->
                    <b><a class="navbar-brand" href="index.html"><p style="color:cadetblue">619|Consomi Tounsi</p></a></b>
            </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                    <ul>
                        <li class="dropdown open">
                            <h5 style="margin-right:20px;text-decoration-color:cadetblue"><a href="#" class="dropdown-toggle pages" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Hello, @ViewBag.Username </h5><span><img src="~/images/down-arrow.png" alt=""></span></a>
                            <ul class="dropdown-menu page-list">
                                <li style="color:burlywood"><i class="material-icons add_ic_call">&#xe97c;</i>@ViewBag.phone</li>
                                <li style="color:burlywood"><i class="material-icons email">&#xe0be;</i>@ViewBag.Email</li>
                                <li>
                                    @if (@ViewBag.authenticated == null)
                                    {
                                        @Html.ActionLink("Login", "Login", "Account")
                                    }
                                    else
                                    {
                                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                        {
                                            @Html.AntiForgeryToken()
                                            <a href="javascript:document.getElementById('logoutForm').submit()" style="text-align:center"><i class="material-icons supervisor_account">&#xe8d3;</i>Log off</a>
                                        }
                                    }
                                </li>
                            </ul>
                        </li>
                    </ul>
        </nav>
    </header>
    <!--Header End-->
    <!-- Page Wrapper -->
    <div id="wrapper" style="margin-top:-72px">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-product-hunt"></i>
                    <span>Products</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item">
                            @Html.ActionLink("View Products", "Index", "Product")
                        </a>
                    </div>
                </div>

            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-box-open"></i>
                    <span>Packs</span>

                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item">
                            @Html.ActionLink("View Packs ", "Index", "Packs")
                        </a>

                    </div>
                </div>
            </li>
            @*<li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                <i class="fas fa-funnel-dollar"></i>
                <span>Discounts</span>
            </a>

            <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">

                    <a class="collapse-item">
                        @Html.ActionLink("View Discounts ", "Index", "Discount")
                    </a>
                </div>
            </div>

        </li>*@

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" @Html.ActionLink("Contacts ", "IndexContact", "Back")
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" @Html.ActionLink("Users ", "Index", "Back")
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-funnel-dollar"></i>
                    <span>Charts</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item">
                            @Html.ActionLink("View Charts Product-Categorie", "Index", "LigneCommandBack")
                        </a>
                        <a class="collapse-item">
                            @Html.ActionLink("View Charts Product-selling", "Index2", "Productt")
                        </a>
                    </div>

                </div>

            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" @Html.ActionLink("Rayon ", "Index", "Rayon")
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        @RenderBody()

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer
    ================================================= -->
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="footer-wrapper">
                    <div class="col-md-3 col-sm-3">
                        <a href=""><h3>619|Consomi Tounsi</h3></a>
                        <ul class="list-inline social-icons">
                            <li><a href="#"><i class="icon ion-social-facebook"></i></a></li>
                            <li><a href="#"><i class="icon ion-social-twitter"></i></a></li>
                            <li><a href="#"><i class="fas fa-mail-bulk"></i></a></li>

                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2">
                        <h6>For individuals</h6>
                        <ul class="footer-links">
                            <li>@Html.ActionLink("Sign Up", "Register", "Account")</li>
                            <li>@Html.ActionLink("Login", "Login", "Account")</li>
                            <li><a href="">Explore</a></li>
                            <li><a href="">Features</a></li>
                            <li><a href="">Language settings</a></li>
                        </ul>
                    </div>

                    <div class="col-md-2 col-sm-2">
                        <h6>@Html.ActionLink("About", "About", "Home")</h6>
                        <ul class="footer-links">
                            <li><a href="">About us</a></li>
                            <li><a href="">Contact us</a></li>
                            <li><a href="">Privacy Policy</a></li>
                            <li><a href="">Terms</a></li>
                            <li><a href="">Help</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <h6>@Html.ActionLink("Contact Us", "Contact", "Home")</h6>
                        <ul class="contact">
                            <li><i class="fas fa-phone"></i> +216 969 25801</li>
                            <li><i class="fas fa-mail-bulk"></i> ConsomiTounsi@gmail.com</li>
                            <li><i class="fas fa-search-location"></i> Pôle Technologique El Ghazela</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <p>Copyright Consomi Tounis 2020. All rights reserved</p>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
    @Scripts.Render("~/ContentAdmin/vendor/jquery/jquery.min.js")
    @Scripts.Render("~/ContentAdmin/vendor/bootstrap/js/bootstrap.bundle.min.js")
    @Scripts.Render("~/ContentAdmin/js/sb-admin-2.min.js")
    @Scripts.Render("~/ContentAdmin/vendor/jquery-easing/jquery.easing.min.js")
    @Scripts.Render("~/ContentAdmin/vendor/chart.js/Chart.min.js")
    @Scripts.Render("~/ContentAdmin/js/demo/chart-area-demo.js")
    @Scripts.Render("~/ContentAdmin/js/demo/chart-pie-demo.js")


</body>

</html>